export const LABELS = {
  auth: {
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    role: 'Rol',
    roleUser: 'Usuario (Líder)',
    roleReviewer: 'Revisor',
    roleAdmin: 'Administrador',
    sede: 'Sede',
    submit: 'Entrar',
    submitRegister: 'Registrarse',
    logout: 'Cerrar Sesión',
  },
  nav: {
    dashboard: 'Panel Principal',
    suppliers: 'Proveedores',
    inventory: 'Inventario',
    orders: 'Pedidos',
    notifications: 'Notificaciones',
    import: 'Importar Datos',
  },
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    search: 'Buscar',
    filter: 'Filtrar',
    loading: 'Cargando...',
    noData: 'No hay datos',
    confirm: 'Confirmar',
    back: 'Volver',
    export: 'Exportar',
    actions: 'Acciones',
  },
  suppliers: {
    title: 'Proveedores',
    addNew: 'Agregar Proveedor',
    nit: 'NIT',
    companyName: 'Razón Social',
    category: 'Categoría',
    advisor: 'Asesor Comercial',
    phone1: 'Teléfono Principal',
    phone2: 'Teléfono Secundario',
    email: 'Correo',
    responseDays: 'Días de Respuesta',
    creditDays: 'Días de Crédito',
  },
  inventory: {
    title: 'Inventario',
    products: 'Productos',
    addProduct: 'Agregar Producto',
    code: 'Código',
    name: 'Nombre',
    unit: 'Unidad de Medida',
    minStock: 'Stock Mínimo',
    currentStock: 'Stock Actual',
    category: 'Categoría',
    movements: 'Movimientos',
    registerMovement: 'Registrar Movimiento',
    priceComparison: 'Comparación de Precios',
    priceHistory: 'Historial de Precios',
    currentPrice: 'Precio Actual',
    previousPrice: 'Precio Anterior',
    variation: 'Variación',
    lowStockAlerts: 'Alertas de Stock Bajo',
    addPrice: 'Registrar Precio',
    linkSupplier: 'Vincular Proveedor',
    unlinkSupplier: 'Desvincular',
    linkedSuppliers: 'Proveedores Vinculados',
    purchaseEntry: 'Entrada por compra',
    exitByRequest: 'Salida por pedido',
    adjustment: 'Ajuste de inventario',
    lossDamage: 'Merma o daño',
  },
  orders: {
    title: 'Pedidos',
    newOrder: 'Nuevo Pedido',
    status: 'Estado',
    sede: 'Sede',
    fecha: 'Fecha',
    draft: 'Borrador',
    sent: 'Enviado',
    inReview: 'En Revisión',
    approved: 'Aprobado',
    dispatched: 'Despachado',
    delivered: 'Entregado',
    rejected: 'Rechazado',
    addItem: 'Agregar Producto',
    quantity: 'Cantidad',
    product: 'Producto',
    suggestedSupplier: 'Proveedor Sugerido',
    suggestedPrice: 'Precio Sugerido',
    highestPrice: 'Precio Más Alto',
    savings: 'Ahorro',
    totalSavings: 'Ahorro Total',
    totalSuggestedCost: 'Costo Sugerido Total',
    totalHighestCost: 'Costo Más Alto Total',
    exportPdf: 'Exportar PDF',
    approve: 'Aprobar',
    reject: 'Rechazar',
    review: 'Revisar',
    dispatch: 'Despachar',
    deliver: 'Marcar Entregado',
    send: 'Enviar Pedido',
  },
  dashboard: {
    title: 'Panel Principal',
    stockSummary: 'Resumen de Stock',
    movementHistory: 'Historial de Movimientos',
    priceTrends: 'Tendencias de Precios',
    savingsHistory: 'Historial de Ahorros',
    totalProducts: 'Total Productos',
    pendingOrders: 'Pedidos Pendientes',
    lowStockItems: 'Productos con Stock Bajo',
    totalSavings: 'Ahorro Total',
    selectProduct: 'Seleccionar producto',
    entries: 'Entradas',
    exits: 'Salidas',
    order: 'Pedido',
    date: 'Fecha',
    savings: 'Ahorro',
  },
  notifications: {
    title: 'Notificaciones',
    markRead: 'Marcar como leída',
    noNotifications: 'No hay notificaciones',
  },
  importData: {
    title: 'Importar Datos',
    importSuppliers: 'Importar Proveedores',
    importProducts: 'Importar Productos',
    dragDrop: 'Arrastra un archivo aquí o haz clic para seleccionar',
    supportedFormats: 'Formatos soportados: CSV, XLSX',
    preview: 'Vista Previa',
    importBtn: 'Importar',
    results: 'Resultados',
    imported: 'Importados',
    skipped: 'Omitidos',
    row: 'Fila',
    reason: 'Motivo',
  },
}
